sonar.projectKey=salesofficeworks

sonar.projectName=Sales Office Works

sonar.projectVersion=1.0
 
sonar.sources=.
 
# Java backend

sonar.java.binaries=management/target/classes
 
# Encoding

sonar.sourceEncoding=UTF-8
 
# Optional (Angular ignore node_modules)

sonar.exclusions=**/node_modules/**,**/*.spec.ts
 
